# Generated by Django 3.0.2 on 2020-02-06 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noscal', '0002_calc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calc',
            name='author',
        ),
    ]
