# Generated by Django 3.0.2 on 2020-02-06 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noscal', '0003_remove_calc_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
