# Generated by Django 3.0.5 on 2020-07-19 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WindOroPametersInAlt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('direction', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('speed', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.CreateModel(
            name='CommonWindParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meteoType', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('meteoPhaseStart', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('windConst', models.IntegerField(blank=True, choices=[(0, 'Not constant'), (1, 'Constant')], default=0, null=True)),
                ('precipitationsRate', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('precipitationType', models.FloatField(blank=True, choices=[(0, 'Without'), (1, 'Rain'), (2, 'Thunderstorm rain'), (3, 'Shower'), (4, 'Drizzle fog'), (5, 'Snow'), (6, 'Snow with rain')], default=0, null=True)),
                ('stab', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='D', max_length=1, null=True)),
                ('roughness', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('windLevels', models.ManyToManyField(blank=True, to='WindOro.WindOroPametersInAlt')),
            ],
        ),
    ]
